steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/data-pipeline/hotel-only:$SHORT_SHA', '-f', 'docker/Dockerfile', '.']
